version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - '4000:3000'
    deploy:
      mode: replicated
      replicas: 1
